package uk.co.mattburns.stolencamerafinder.gui;

import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JFormattedTextField.AbstractFormatter;

import uk.co.mattburns.stolencamerafinder.SearchObserver;
import uk.co.mattburns.stolencamerafinder.StolenCamera;
import uk.co.mattburns.stolencamerafinder.StolenCameraDatabase;
import uk.co.mattburns.stolencamerafinder.StolenCameraFinder;
import uk.co.mattburns.stolencamerafinder.StolenCameraFinderImpl;
import uk.co.mattburns.stolencamerafinder.StolenCameraFinder.TAG_SEARCH_MODE;
import uk.co.mattburns.stolencamerafinder.scrapers.flickr.StolenCameraDatabaseFactory;
import uk.co.mattburns.stolencamerafinder.util.FlickrFactory;
import uk.co.mattburns.stolencamerafinder.util.FlickrPhotos;

import com.aetrion.flickr.photos.Photo;

/**
 * 
 * @author matt
 */
public class Webstart extends javax.swing.JFrame implements SearchObserver {

    private static final long serialVersionUID = 1L;
    private static final String SEARCH = "Search";
    private static final String STOP = "Stop";
    private final Set<JComponent> editableElements = new HashSet<JComponent>();

    private StolenCameraDatabase database;

    public Webstart() {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        initComponents();
        tagsButtonGroup.add(allTagsRadioButton);
        tagsButtonGroup.add(anyTagsRadioButton);

        editableElements.add(urlTextField);
        editableElements.add(errorStringTextField);
        editableElements.add(maxTakenDateFormattedTextField);
        editableElements.add(tagsTextField);
        editableElements.add(allTagsRadioButton);
        editableElements.add(anyTagsRadioButton);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tagsButtonGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        basicPanel = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        urlLabel = new javax.swing.JLabel();
        urlTextField = new javax.swing.JTextField();
        errorStringLabel = new javax.swing.JLabel();
        errorStringTextField = new javax.swing.JFormattedTextField();
        advancedPanel = new javax.swing.JPanel();
        advancedSearchLabel = new javax.swing.JLabel();
        tagsLabel = new javax.swing.JLabel();
        tagsTextField = new javax.swing.JTextField();
        allTagsRadioButton = new javax.swing.JRadioButton();
        anyTagsRadioButton = new javax.swing.JRadioButton();
        maxTakenDateLabel = new javax.swing.JLabel();
        maxTakenDateFormattedTextField = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        logScrollPane = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        logLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("stolencamerafinder");

        searchLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchLabel.setText("Stolen Camera Details");

        urlLabel.setText("URL");
        urlLabel.setMaximumSize(null);
        urlLabel.setMinimumSize(null);

        urlTextField.setText("http://hudson/view/Radiator/");
        urlTextField.setToolTipText("The URL to poll");

        errorStringLabel.setText("Error string");
        errorStringLabel.setMaximumSize(new java.awt.Dimension(100, 15));
        errorStringLabel.setMinimumSize(new java.awt.Dimension(100, 15));

        errorStringTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
                new javax.swing.text.DateFormatter()));
        errorStringTextField.setText("RED");
        errorStringTextField
                .setToolTipText("Wake the screen if URL source contains this text");

        javax.swing.GroupLayout basicPanelLayout = new javax.swing.GroupLayout(basicPanel);
        basicPanel.setLayout(basicPanelLayout);
        basicPanelLayout.setHorizontalGroup(basicPanelLayout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                basicPanelLayout.createSequentialGroup().addGroup(
                        basicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                                basicPanelLayout.createSequentialGroup().addGap(10, 10, 10).addComponent(searchLabel,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)).addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                basicPanelLayout.createSequentialGroup().addContainerGap().addGroup(
                                        basicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                false).addComponent(errorStringLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(
                                                urlLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 121,
                                                Short.MAX_VALUE)).addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                                        basicPanelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(errorStringTextField,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                                                .addComponent(urlTextField,
                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))))
                        .addContainerGap()));
        basicPanelLayout.setVerticalGroup(basicPanelLayout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                basicPanelLayout.createSequentialGroup().addContainerGap().addComponent(searchLabel).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(
                        basicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(
                                urlTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(urlLabel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                                basicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(errorStringLabel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(
                                                errorStringTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(28,
                                Short.MAX_VALUE)));

        jTabbedPane1.addTab("Basic", basicPanel);

        advancedSearchLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        advancedSearchLabel.setText("Extra Options to help narrow the search");
        advancedSearchLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                advancedSearchLabelMouseClicked(evt);
            }
        });

        tagsLabel.setText("Tagged with");
        tagsLabel.setMaximumSize(new java.awt.Dimension(100, 15));
        tagsLabel.setMinimumSize(new java.awt.Dimension(100, 15));

        tagsTextField
                .setToolTipText("<html>\n<p>Enter a comma-separated list of tags.</p>\n\n<p>e.g:</p>\n<blockquote>windmill,wind,wind farm</blockquote></html>");
        tagsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagsTextFieldActionPerformed(evt);
            }
        });

        allTagsRadioButton.setSelected(true);
        allTagsRadioButton.setText("all");
        allTagsRadioButton.setToolTipText("Selecting \"all\" will only find photos with all of the tags listed");
        allTagsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allTagsRadioButtonActionPerformed(evt);
            }
        });

        anyTagsRadioButton.setText("any");
        anyTagsRadioButton.setToolTipText("Selecting \"any\" will find photos with any of the tags listed");

        maxTakenDateLabel.setText("Taken before");

        maxTakenDateFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
                new javax.swing.text.DateFormatter()));
        maxTakenDateFormattedTextField
                .setToolTipText("<html><p>Only search in photos that were taken before this date</p>\n<p>e.g.</p>\n<blockquote>31-May-2009</blockquote></html>");

        javax.swing.GroupLayout advancedPanelLayout = new javax.swing.GroupLayout(advancedPanel);
        advancedPanel.setLayout(advancedPanelLayout);
        advancedPanelLayout
                .setHorizontalGroup(advancedPanelLayout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                advancedPanelLayout
                                        .createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(
                                                advancedPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(advancedSearchLabel,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 503,
                                                                Short.MAX_VALUE)
                                                        .addGroup(
                                                                advancedPanelLayout
                                                                        .createSequentialGroup()
                                                                        .addGroup(
                                                                                advancedPanelLayout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                false)
                                                                                        .addComponent(
                                                                                                maxTakenDateLabel,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                        .addComponent(
                                                                                                tagsLabel,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                121, Short.MAX_VALUE))
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addGroup(
                                                                                advancedPanelLayout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(
                                                                                                advancedPanelLayout
                                                                                                        .createSequentialGroup()
                                                                                                        .addComponent(
                                                                                                                tagsTextField,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                272,
                                                                                                                Short.MAX_VALUE)
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                        .addComponent(
                                                                                                                allTagsRadioButton)
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                        .addComponent(
                                                                                                                anyTagsRadioButton))
                                                                                        .addComponent(
                                                                                                maxTakenDateFormattedTextField,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                370, Short.MAX_VALUE))))
                                        .addContainerGap()));
        advancedPanelLayout.setVerticalGroup(advancedPanelLayout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                advancedPanelLayout.createSequentialGroup().addContainerGap().addComponent(advancedSearchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(
                                advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tagsLabel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(tagsTextField,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(anyTagsRadioButton).addComponent(allTagsRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                                advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(maxTakenDateLabel).addComponent(maxTakenDateFormattedTextField,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(28,
                                Short.MAX_VALUE)));

        jTabbedPane1.addTab("Extra Options", advancedPanel);

        logTextArea.setColumns(20);
        logTextArea.setEditable(false);
        logTextArea.setRows(5);
        logScrollPane.setViewportView(logTextArea);

        logLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logLabel.setText("Log");
        logLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logLabelMouseClicked(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.setToolTipText("Toggle Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE).addComponent(
                        logLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE).addComponent(
                        logScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE).addComponent(
                        searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(searchButton,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
                                        statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                        javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(logLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
                                        logScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout.createSequentialGroup().addContainerGap().addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jPanel1,
                                javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jTabbedPane1,
                                javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 531,
                                Short.MAX_VALUE)).addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addContainerGap().addComponent(jTabbedPane1,
                        javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jPanel1,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE).addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tagsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagsTextFieldActionPerformed
    }//GEN-LAST:event_tagsTextFieldActionPerformed

    private void toggleEditableElements(boolean isEnabled) {
        for (JComponent component : editableElements) {
            component.setEnabled(isEnabled);
        }
    }

    private void allTagsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allTagsRadioButtonActionPerformed
    }//GEN-LAST:event_allTagsRadioButtonActionPerformed

    private void advancedSearchLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_advancedSearchLabelMouseClicked
    }//GEN-LAST:event_advancedSearchLabelMouseClicked

    private void logLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logLabelMouseClicked
    }//GEN-LAST:event_logLabelMouseClicked

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        if (searchButton.getText().equals(SEARCH)) {
            startSearch();
        } else {
            stopSearch();
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void startSearch() {
        searchButton.setText(STOP);
        toggleEditableElements(false);
        finderThread = new Thread(new FinderThread());
        finderThread.start();
    }

    private void stopSearch() {
        searchButton.setText(SEARCH);
        toggleEditableElements(true);
    }

    private void appendLogText(String logText) {
        Date now = Calendar.getInstance().getTime();
        DateFormat df = SimpleDateFormat.getTimeInstance(DateFormat.MEDIUM);
        logTextArea.append(df.format(now) + " : " + logText + "\n");
    }

    private void updateStatus() {
        String status = "Photos searched : " + photosSearched;
        statusLabel.setText(status);
    }

    @Override
    public boolean shouldAbort() {
        return searchButton.getText().equals(SEARCH);
    }

    @Override
    public void reportPhotoFound(Photo photo) {
        updateStatus();
        appendLogText("Photo found!! : " + photo.getUrl());

        String serial = FlickrPhotos.getSerialFromPhoto(photo);
        StolenCamera photoReported = database.getCamera(serial);
        if (photoReported.getPhotoID() != null) {
            Photo flickrPhotoReported = FlickrFactory.getPhoto(photoReported.getPhotoID());
            appendLogText("PLEASE POST A COMMENT ON THIS PHOTO TO LET THEM KNOW! : " + flickrPhotoReported.getUrl());
            //                TODO: Not yet implemented
            //            FlickrPhotos.reportStolenCameraInComments(photo, flickrPhotoReported);
        }
    }

    @Override
    public void reportPhotoSearched(Photo photo) {
        photosSearched++;
        updateStatus();
    }

    private class FinderThread implements Runnable {

        private FinderThread() {
        }

        public void run() {

            for (int i = 0 ; i < 10 ; i ++) {
                appendLogText("i = " + i);
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                if (i == 1) {
                    appendLogText("sleeping monitor");
                    
                    try {
                        Runtime.getRuntime().exec("poweroff monitor_off");
                    } catch (IOException e) {
                        appendLogText(e.getMessage() + e.getStackTrace());
                        // TODO Auto-generated catch block
                        e.printStackTrace();
                    }
                }
                if (i == 8) {
                    appendLogText("waking monitor");
                    
                    try {
                        Runtime.getRuntime().exec("poweroff monitor_on");
                    } catch (IOException e) {
                        appendLogText(e.getMessage() + e.getStackTrace());
                        // TODO Auto-generated catch block
                        e.printStackTrace();
                    }
                }
            }
            appendLogText("finished");
        }
    }

    /**
     * @param args
     *            the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Webstart().setVisible(true);
            }
        });
    }

    private Thread finderThread;
    private int photosSearched = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel advancedPanel;
    private javax.swing.JLabel advancedSearchLabel;
    private javax.swing.JRadioButton allTagsRadioButton;
    private javax.swing.JRadioButton anyTagsRadioButton;
    private javax.swing.JPanel basicPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel logLabel;
    private javax.swing.JScrollPane logScrollPane;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JFormattedTextField maxTakenDateFormattedTextField;
    private javax.swing.JLabel maxTakenDateLabel;
    private javax.swing.JFormattedTextField errorStringTextField;
    private javax.swing.JLabel errorStringLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JLabel urlLabel;
    private javax.swing.JTextField urlTextField;
    private javax.swing.JLabel statusLabel;
    private javax.swing.ButtonGroup tagsButtonGroup;
    private javax.swing.JLabel tagsLabel;
    private javax.swing.JTextField tagsTextField;
    // End of variables declaration//GEN-END:variables
}
